apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: custom-ansible3:latest
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-service
spec:
  selector:
    app: ansible
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
